### ISSUE TITLE
java.lang.RuntimeException: Failed to call observer method

### ISSUE THREAD

**Issue by mibrahimdev** [motorro/AppUpdateWrapper#14]
```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.tons.consumer/ru.handh.tons.ui.selectstorewitharea.SelectStoreWithAreaActivity}: java.lang.RuntimeException: Failed to call observer method
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4013)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4045)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7037)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by mibrahimdev** [comment]
I don't know why this hapening

**Comment by motorro** [comment]
@MohamedISoliman are you sure the library causes the error?
Do you have any steps to reproduce? Did not see this kind of errors in any of my applications using this wrapper.
I need a list of `Caused by` to guess what may be a problem at least
